### ISSUE TITLE
esa_snappy.ini file missing 

### ISSUE THREAD

**Issue by Boorhin** [senbox-org/esa-snappy#4]
Hi,
I have had loads of struggles to install on Ubuntu 22.04 LTS. The documentation being not up to date and the jpy repo documentation showing content from the devs towards users. 
https://forum.step.esa.int/t/install-snappy-on-ubuntu-22-04/42732/3
It is not specified how to configure the RAM when launching the module with esa_snappy.ini. The way this file should be formatted is not specified either.
Could you provide a source for it so I can edit it?
Or is there a command that allows to setup the allocated RAM on the fly?
Thanks in advance

**Comment by Boorhin** [comment]
I discovered that the memory allocation is hard coded in __init__.py !
Why not letting the system manage this ? Python heartbeat should be able to cope.

**Comment by dolaf** [comment]
> I discovered that the memory allocation is hard coded in init.py !

No, it isn't. Just a default initialisation value is given there.

>`Why not letting the system manage this ?`

That's how it is done. After a successful installation, the java_max_mem value in esa_snappy.ini should be the same as the Xmx parameter given in SNAP Desktop (Tools --> Options --> Performance --> VM Parameters).

If really needed, esa_snappy.ini can just be edited and the value changed. See also last paragraph in esa_snappy installation instructions:
[https://senbox.atlassian.net/wiki/spaces/SNAP/pages/2499051521/Configure+Python+to+use+the+new+SNAP-Python+esa+snappy+interface+SNAP+version+10](https://senbox.atlassian.net/wiki/spaces/SNAP/pages/2499051521/Configure+Python+to+use+the+new+SNAP-Python+esa+snappy+interface+SNAP+version+10)

**Comment by Boorhin** [comment]
Ok, so my confusion comes from the fact that snappy.ini was not on my system. With the new installation it is.
Thanks
